namespace Authware.AspNetCore.Models;

/// <summary>
///     Represents a previous request made by a user for a specific API
/// </summary>
public class ApiRequest
{
    [JsonConstructor]
    public ApiRequest(Guid apiId, Guid id, DateTime dateCreated, Dictionary<string, string>? parameters = null)
    {
        Parameters = parameters;
        ApiId = apiId;
        Id = id;
        DateCreated = dateCreated;
    }

    /// <summary>
    ///     The ID of the request, this is generated by the API and can be seen in your applications audit logs
    /// </summary>
    [JsonPropertyName("id")]
    public Guid Id { get; set; }

    /// <summary>
    ///     The ID of the API that was executed
    /// </summary>
    [JsonPropertyName("api_id")]
    public Guid ApiId { get; set; }

    /// <summary>
    ///     The parameters the user sent, this does not include parameters that already have a value set in your application
    /// </summary>
    [JsonPropertyName("parameters")]
    public Dictionary<string, string>? Parameters { get; set; }

    /// <summary>
    ///     The date the request was sent
    /// </summary>
    [JsonPropertyName("date_created")]
    public DateTime DateCreated { get; set; }
}